# -*- coding: utf-8 -*-
"""биокад ML биоинформатика

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmj9Idbw7ULUmt-EPLO5xotpi4DfoDdt

ΔG=RT⋅ln(Kd), где Kd - константа диссоциации
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

# Загрузка данных. Я их уже предварительно систематизировала (заменила всп запятые на точки, из столбца Temperature в строчках убрала слово (assumed)).
data = pd.read_csv("skempi20.csv", sep=';')

# Константы
R =  0.001986  # газовая постоянная в в ккал/(моль·K)

# Вычисляем ddG
data['ddG'] = R * data['Temperature'] * np.log(data['Affinity_mut_parsed'] / data['Affinity_wt_parsed'])

# Создаем целевую переменную: 1 если ddG > 0 (ухудшение связывания), 0 если ddG <= 0 (улучшение или без изменений)
data['target'] = (data['ddG'] > 0).astype(int)

# Выбор данных для анализа и подготовка признаков
features = data[['iMutation_Location(s)', 'Affinity_mut_parsed',
                 'Affinity_wt_parsed', 'Temperature', 'Protein 1', 'Protein 2']].copy()

# Кодируем категориальные признаки
label_encoders = {}
for col in ['iMutation_Location(s)', 'Protein 1', 'Protein 2']:
    le = LabelEncoder()
    features[col] = le.fit_transform(features[col].astype(str))  # преобразуем в строку перед кодированием
    label_encoders[col] = le

# Заполняем пропущенные значения
num_cols = ['Affinity_mut_parsed', 'Affinity_wt_parsed', 'Temperature']
cat_cols = ['iMutation_Location(s)', 'Protein 1', 'Protein 2']

# Заполняем пропущенные значения в числовых признаках средними значениями по столбцу
num_imputer = SimpleImputer(strategy='mean')
features[num_cols] = num_imputer.fit_transform(features[num_cols])

# Заполняем пропущенные значения в категориальных признаках самым частым значением
cat_imputer = SimpleImputer(strategy='most_frequent')
features[cat_cols] = cat_imputer.fit_transform(features[cat_cols])

# Масштабируем числовые признаки
scaler = StandardScaler()
features[num_cols] = scaler.fit_transform(features[num_cols])

# Разделение данных
X_train, X_test, y_train, y_test = train_test_split(features, data['target'], test_size=0.2, random_state=42)

# Обучение моделей
# 1. Логистическая регрессия
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# 2. Модель, поддерживающая NaN (пустые ячейки)
hgb = HistGradientBoostingClassifier()
hgb.fit(X_train, y_train)
y_pred_hgb = hgb.predict(X_test)
print("\nHistGradientBoosting Accuracy:", accuracy_score(y_test, y_pred_hgb))
print(classification_report(y_test, y_pred_hgb))